# Generated by Django 4.2.6 on 2023-11-26 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(default='', max_length=100)),
                ('descricao', models.TextField(default='Escreva sua descrição', max_length=150)),
                ('status', models.CharField(choices=[('analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='analise', max_length=10)),
                ('dataPostagem', models.DateTimeField(auto_now_add=True)),
                ('arqMidia', models.ImageField(blank=True, null=True, upload_to='arqmidia/%Y/%m/%d/')),
                ('arqCartaz', models.ImageField(blank=True, null=True, upload_to='arqcartaz/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_midia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHistorico', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('concluido', models.BooleanField(default='False')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia_list_historico', to='gestor.midia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_historico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacao', models.CharField(choices=[('Like', 'like'), ('Dislike', 'dislike'), ('No_react', 'no_react')], default='No_react', max_length=10)),
                ('comentario', models.CharField(default='Traga o seu comentario', max_length=1000)),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia_list_Feedback', to='gestor.midia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, choices=[('masteruser', 'MasterUser'), ('reportuser', 'ReportUser'), ('midiauser', 'MidiaUser')], default='null', max_length=10, null=True)),
                ('motivacao', models.CharField(default='Maximo de 250 caracteres', max_length=250)),
                ('status', models.CharField(choices=[('preenchendo', 'Preenchendo'), ('analise', 'Em_Analise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='preenchendo', max_length=15)),
                ('atividade', models.BooleanField(default='False')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(default='Escreva sua mensagem', max_length=200)),
                ('contexto', models.CharField(choices=[('notificacao', 'Notificacao'), ('pedido_de_cargo', 'Pedido_De_Cargo'), ('suporte', 'Suporte'), ('reportar', 'Reportar')], default='suporte', max_length=15)),
                ('dataMensagem', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_remetente', to=settings.AUTH_USER_MODEL)),
                ('userDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_destinatario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(default='Informe a sua mensagem', max_length=500)),
                ('status', models.BooleanField(default='False')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_suporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaReporte', models.CharField(choices=[('Conteudo_Inadequado', 'conteudo_inadequado'), ('Problema_de_Legenda', 'problema_de_legenda'), ('Problema_de_Reproducao', 'problema_de_reproducao'), ('Outro', 'outro')], default='reporte', max_length=23)),
                ('texto', models.CharField(default='Descreva o problema encontrado', max_length=500)),
                ('status', models.BooleanField(default='False')),
                ('midia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midia_list_reporte', to='gestor.midia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_user_reporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
