# Generated by Django 4.2.6 on 2023-11-27 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(choices=[('assets/fotos/foto1.png', 'Foto1'), ('assets/fotos/foto2.png', 'Foto2'), ('assets/fotos/foto3.png', 'Foto3'), ('assets/fotos/foto4.png', 'Foto4')], default='assets/fotos/foto1.png', upload_to='assets/fotos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
