# Generated by Django 4.2.6 on 2023-10-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcolaborador',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
