# Generated by Django 4.2.6 on 2023-11-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_perfiluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='foto',
            field=models.ImageField(choices=[('assets/fotos/foto1.jpeg', 'Foto1'), ('assets/fotos/foto2.jpeg', 'Foto2'), ('assets/fotos/foto3.jpeg', 'Foto3'), ('assets/fotos/foto4.jpeg', 'Foto4')], default='assets/fotos/foto1.png', upload_to='assets/fotos/'),
        ),
    ]
