# Generated by Django 4.2.6 on 2023-10-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_perfilcolaborador_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcolaborador',
            name='name',
        ),
    ]
