# Generated by Django 4.2.6 on 2023-11-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_perfiluser_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUser',
        ),
    ]
