# Generated by Django 4.2.6 on 2023-10-24 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0003_remove_perfilcolaborador_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestePerfilColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('textoMotivacao', models.TextField(blank=True, default='Porque você quer ser coloborador?', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, default='Escreva sua descrição', max_length=150)),
                ('status', models.CharField(choices=[('analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='analise', max_length=10)),
                ('dataPostagem', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
