# Generated by Django 4.2.6 on 2023-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_delete_perfiluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcolaborador',
            name='motivacao',
            field=models.CharField(default='Maximo de 250 caracteres', max_length=1500),
        ),
    ]
