# Generated by Django 4.2.6 on 2023-10-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0005_alter_midia_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default='False')),
            ],
        ),
        migrations.AddField(
            model_name='perfilcolaborador',
            name='atividade',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='perfilcolaborador',
            name='cargo',
            field=models.CharField(choices=[('masteruser', 'MasterUser'), ('reportuser', 'ReportUser'), ('midiauser', 'MidiaUser')], default='analise', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilcolaborador',
            name='status',
            field=models.CharField(choices=[('analise', 'Em_Analise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='analise', max_length=10),
        ),
        migrations.AlterField(
            model_name='midia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_midia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserRequestePerfilColaborador',
        ),
        migrations.AddField(
            model_name='userhistorico',
            name='midia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia_list_historico', to='gestor.midia'),
        ),
        migrations.AddField(
            model_name='userhistorico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_historico', to=settings.AUTH_USER_MODEL),
        ),
    ]
