# Generated by Django 4.2.6 on 2023-11-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_alter_perfilcolaborador_motivacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcolaborador',
            name='motivacao',
            field=models.CharField(default='Quero ser um colaborador!!!!!', max_length=1500),
        ),
    ]
