# Generated by Django 4.2.6 on 2023-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_userhistorico_perfilcolaborador_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='argMidia',
            field=models.ImageField(blank=True, null=True, upload_to='arqmidia/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='midia',
            name='arqCartaz',
            field=models.ImageField(blank=True, null=True, upload_to='arqcartaz/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='descricao',
            field=models.TextField(default='Escreva sua descrição', max_length=150),
        ),
    ]
