# Generated by Django 4.2.1 on 2023-10-28 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0007_midia_argmidia_midia_arqcartaz_alter_midia_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('mensagem', models.CharField(default='Escreva sua mensagem', max_length=200)),
                ('idMensagem', models.AutoField(primary_key=True, serialize=False)),
                ('contexto', models.CharField(choices=[('pedido_de_cargo', 'Pedido_De_Cargo'), ('suporte', 'Suporte'), ('reportar', 'Reportar')], default='suporte', max_length=15)),
                ('dataMensagem', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_remetente', to=settings.AUTH_USER_MODEL)),
                ('userDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_destinatario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
