# Generated by Django 4.2.1 on 2023-10-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0008_mensagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagens',
            name='idMensagem',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
