# Generated by Django 4.2.6 on 2023-10-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0009_alter_mensagens_idmensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='argMidia',
        ),
        migrations.AddField(
            model_name='midia',
            name='arqMidia',
            field=models.ImageField(blank=True, null=True, upload_to='arqmidia/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='FormularioReporte',
            fields=[
                ('idFormulario', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('arqMidia', models.ImageField(blank=True, null=True, upload_to='arqmidia/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
