# Generated by Django 4.2.6 on 2023-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_remove_midia_argmidia_midia_arqmidia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagens',
            name='contexto',
            field=models.CharField(choices=[('notificacao', 'Notificacao'), ('pedido_de_cargo', 'Pedido_De_Cargo'), ('suporte', 'Suporte'), ('reportar', 'Reportar')], default='suporte', max_length=15),
        ),
    ]
