# Generated by Django 4.2.6 on 2023-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_alter_mensagens_contexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioreporte',
            name='texto',
            field=models.CharField(default='Descreva o problema encontrado', max_length=500),
        ),
    ]
