# Generated by Django 4.2.6 on 2023-10-28 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0012_formularioreporte_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(default='Informe a sua mensagem', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_suporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
