# Generated by Django 4.2.6 on 2023-10-28 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0013_formulariosuporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacao', models.CharField(choices=[('Like', 'like'), ('Dislike', 'dislike'), ('No_react', 'no_react')], default='No_react', max_length=10)),
                ('comentario', models.CharField(default='Traga o seu comentario', max_length=1000)),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia_list_Feedback', to='gestor.midia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
