# Generated by Django 4.2.6 on 2023-10-30 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0014_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagens',
            name='idMensagem',
        ),
        migrations.AddField(
            model_name='mensagens',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensagens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_remetente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagens',
            name='userDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list_destinatario', to=settings.AUTH_USER_MODEL),
        ),
    ]
