# Generated by Django 4.2.6 on 2023-10-30 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0015_remove_mensagens_idmensagem_mensagens_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioreporte',
            name='idFormulario',
        ),
        migrations.AddField(
            model_name='formularioreporte',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formularioreporte',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_user_suporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
