# Generated by Django 4.2.6 on 2023-10-30 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor', '0016_remove_formularioreporte_idformulario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioreporte',
            name='arqMidia',
        ),
        migrations.AddField(
            model_name='formularioreporte',
            name='midia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midia_list_reporte', to='gestor.midia'),
        ),
        migrations.AlterField(
            model_name='formularioreporte',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_user_reporte', to=settings.AUTH_USER_MODEL),
        ),
    ]
