# Generated by Django 4.2.6 on 2023-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0017_remove_formularioreporte_arqmidia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioreporte',
            name='categoriaReporte',
            field=models.CharField(choices=[('Conteudo_Inadequado', 'conteudo_inadequado'), ('Problema_de_Legenda ', 'problema_de_legenda'), ('Problema_de_Reproducao', 'problema_de_reproducao'), ('Outro', 'outro')], default='reporte', max_length=23),
        ),
    ]
