# Generated by Django 4.2.6 on 2023-11-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0018_formularioreporte_categoriareporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcolaborador',
            name='cargo',
            field=models.CharField(choices=[('masteruser', 'MasterUser'), ('reportuser', 'ReportUser'), ('midiauser', 'MidiaUser')], default='midiauser', max_length=10),
        ),
    ]
