# Generated by Django 4.2.6 on 2023-11-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0019_alter_perfilcolaborador_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistorico',
            name='dataHustorico',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
