# Generated by Django 4.2.6 on 2023-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0020_userhistorico_datahustorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
