# Generated by Django 4.2.6 on 2023-11-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0022_formulariosuporte_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistorico',
            old_name='dataHustorico',
            new_name='dataHistorico',
        ),
    ]
