# Generated by Django 4.2.6 on 2023-11-13 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0024_alter_userhistorico_datahistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistorico',
            name='dataHistorico',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
