# Generated by Django 4.2.6 on 2023-11-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0025_alter_userhistorico_datahistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioreporte',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
