# Generated by Django 4.2.6 on 2023-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0027_alter_formularioreporte_categoriareporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcolaborador',
            name='motivacao',
            field=models.CharField(default='Maximo de 250 caracteres', max_length=250),
        ),
    ]
