# Generated by Django 4.2.6 on 2023-11-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0029_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(choices=[('assets/fotos/foto1.jpg', 'Foto1')], default='assets/fotos/foto1.jpg', upload_to='fssets/fotos/'),
        ),
    ]
