# Generated by Django 4.2.6 on 2023-11-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0032_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcolaborador',
            name='status',
            field=models.CharField(choices=[('preenchendo', 'Preenchendo'), ('analise', 'Em_Analise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='preenchendo', max_length=15),
        ),
    ]
