# Generated by Django 4.2.6 on 2023-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0033_alter_perfilcolaborador_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcolaborador',
            name='cargo',
            field=models.CharField(blank=True, choices=[('masteruser', 'MasterUser'), ('reportuser', 'ReportUser'), ('midiauser', 'MidiaUser')], default='null', max_length=10, null=True),
        ),
    ]
